channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - attrs=18.2.0
  - backcall=0.1.0
  - bcftools=1.9
  - bedtools=2.27.1
  - biopython=1.72
  - blas=1.0
  - bokeh=1.0.2
  - bwa=0.7.17
  - bzip2=1.0.6
  - ca-certificates=2018.11.29
  - certifi=2018.11.29
  - click=7.0
  - cloudpickle=0.6.1
  - coreutils=8.30
  - curl=7.61.0
  - cycler=0.10.0
  - cython=0.29.1
  - cytoolz=0.9.0.1
  - dask=1.0.0
  - dask-core=1.0.0
  - dbus=1.13.0
  - decorator=4.3.0
  - distributed=1.25.0
  - entrypoints=0.2.3
  - expat=2.2.5
  - fastcluster=1.1.25
  - fastqc=0.11.8
  - fontconfig=2.13.1
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - gmp=6.1.2
  - gst-plugins-base=1.12.5
  - gstreamer=1.12.5
  - h5py=2.8.0
  - hdf5=1.10.4
  - heapdict=1.0.0
  - htslib=1.9
  - icu=58.2
  - intel-openmp=2019.1
  - ipykernel=5.1.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.1
  - jinja2=2.10
  - jpeg=9c
  - jsonschema=3.0.0a3
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - krb5=1.14.6
  - libcurl=7.61.1
  - libdeflate=1.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=7.3.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.2.0
  - libiconv=1.15
  - libpng=1.6.36
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libstdcxx-ng=7.3.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - llvmlite=0.26.0
  - locket=0.2.0
  - lz4-c=1.8.3
  - markupsafe=1.1.0
  - matplotlib=3.0.2
  - matplotlib-base=3.0.2
  - matplotlib-venn
  - mistune=0.8.4
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - msgpack-python=0.6.0
  - mysql-connector-c=6.1.6
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.2
  - numba=0.41.0
  - numpy=1.15.4
  - numpy-base=1.15.4
  - olefile=0.46
  - openblas=0.2.20
  - openjdk=11.0.1
  - openssl=1.0.2p
  - packaging=18.0
  - pairix=0.3.6
  - pairtools=0.2.0
  - pandas=0.23.4
  - pandoc=2.5
  - pandocfilters=1.4.2
  - parallel=20181022
  - parso=0.3.1
  - partd=0.3.9
  - patsy=0.5.1
  - pbgzip=2016.08.04
  - pcre=8.41
  - perl=5.26.2
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=5.3.0
  - pip=18.1
  - prometheus_client=0.4.2
  - prompt_toolkit=2.0.7
  - psutil=5.4.8
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pybedtools=0.8.0
  - pyfaidx=0.5.5.2
  - pygments=2.3.0
  - pyparsing=2.3.0
  - pyqt=4.11.4
  - pyrsistent=0.14.7
  - pysam=0.15.1
  - python=3.6.7
  - python-dateutil=2.7.5
  - pytz=2018.7
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=4.8.7
  - qtconsole=4.4.3
  - readline=7.0
  - samtools=1.9
  - scipy=1.2.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - seqtk=1.3
  - setuptools=40.6.2
  - sip=4.18
  - six=1.11.0
  - sortedcontainers=2.1.0
  - sqlite=3.26.0
  - sra-tools=2.9.1_1
  - statsmodels=0.9.0
  - tabix=0.2.6
  - tblib=1.3.2
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=5.1.1
  - traitlets=4.3.2
  - ucsc-bedgraphtobigwig=357
  - ucsc-bigwigtobedgraph=357
  - ucsc-fetchchromsizes=357
  - wcwidth=0.1.7
  - wheel=0.32.3
  - widgetsnbextension=3.4.2
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zict=0.1.3
  - zlib=1.2.11
  - pip:
    - awscli==1.16.69
    - bioframe
    - bleach==3.0.2
    - boto3==1.9.59
    - botocore==1.12.59
    - chardet==3.0.4
    - colorama==0.3.9
    - cooler==0.7.11
    - cooltools==0.1.0
    - dill==0.2.8.2
    - docutils==0.14
    - idna==2.7
    - jmespath==0.9.3
    - git+https://github.com/nvictus/lavaburst.git
    - multiprocess==0.70.6.1
    - natsort==5.5.0
    - ncls==0.0.32
    - numexpr==2.6.8
    - pyasn1==0.4.4
    - pybbi
    - pyranges==0.0.16
    - pyrle==0.0.13
    - requests==2.20.1
    - rsa==3.4.2
    - s3fs==0.2.0
    - s3transfer==0.1.13
    - scikit-learn==0.20.1
    - sorted-nearest==0.0.10
    - tables==3.4.4
    - tabulate==0.8.2
    - urllib3==1.24.1
    - webencodings==0.5.1
